### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Universe-Viewer-Dev#1]
Hi. I wanted to ask is there an approximate release date of the beta client?

**Comment by CaseyraeStarfinder** [comment]
Greetings,

The release date for the viewer is a bit of a ways off.  In order for me to determine that a viewer version can be released the following must happen:

1. There are no major problems found by coverity scans that would knowingly cause problems or slow the viewer or user's pc down.
2. The Viewer Development Work Group must test the viewer first and determine any bugs and implement fixes for bugs found.
3. Code must be clean and meet the standards set by the voting core developers of the Second Galaxy Development Team.
4. Builds for each operating system must be completed with proper signing in order for them to install and work properly on that operating system.

When these standards are met then a new version is ready for official release.

It should be noted that we are working on ensuring that all grids using the Virtual Universe and WhiteCore-Sim architectures will have compatibility and complete support along with our own proprietary grid architecture.

With this being said, should everything go according to plan we expect to have the first version (though it may be a beta version) available before the Christmas Break.

Best Regards,

Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
Hi I want to figure it out myself how to compile the client, installed all when prescribed to configure autobuild-ReleaseOS produces here that http://prntscr.com/d2fqaz tell me how to fix this really want to learn yourself to assemble it.

**Comment by CaseyraeStarfinder** [comment]
Greetings

At a minimum you need to have Visual Studios 2013 Community Edition installed.  However Visual Studio 2015 should work just fine.  The reason you cant open the .sln file is because you don't have the necessary minimum version of Visual Studios installed.

This question has been answered.  Should you have issues or feature requests please open a separate issue for each so we do not get ourselves confused.

Best Regards,

Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
@CaseyraeStarfinder  Thanks for the help, compile without error.
