### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Universe-Viewer-Dev#4]
Hi. Error client Assembly http://prntscr.com/d419l9

**Comment by CaseyraeStarfinder** [comment]
Greetings,

As has been stated in the commit message for commit: https://github.com/Virtual-Universe/Universe-Viewer-Dev/commit/65d3d9217d95b27b0c210914362240f24b2f4e5a we have withheld the files necessary to build he viewer for the moment while we are in the process of getting the viewer code ready to provide official build files.  This may take a day or two and you will see errors during attempts to build until we provide those files.

Best Regards,

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by LifeGold** [comment]
The first error was eliminated but got stuck on this, tried different versions but you need to put never found. http://prntscr.com/d43d93

**Comment by CaseyraeStarfinder** [comment]
Greetings

As has been already stated you are getting this error because you will need our specific build files which we have not yet provided.  Once we provide those with our specific building instructions this error will go away.

There is still much more we need to do before we can provide those files.  We ask everyone to please be patient while the Viewer Development Work Group continues its wok to get the viewers ready.

This issue will go away once the required build files are provided.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
Morning,

The best thing to do here is let them get the viewer ready before trying to build it yourself.  This way they can avoid problems that actually aren't really there.  Remember as they push commits they are building the viewer internally and testing prior to the commits being pushed to the repository so they do know things are working.  

They will let everyone know when its safe for people to build the viewer themselves.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by LifeGold** [comment]
@emperorstarfinder I realized that now is the elimination of errors in the client.  If it was fixed with a compilation of our team could help you find errors and notify you about them.

**Comment by emperorstarfinder** [comment]
Good morning

At the moment the viewer is not yet ready for that phase.  Casey and Briakallista will let everyone know when they believe it is ready for that phase.  There is still a number of things they need to do before that can happen.  I would encourage patience for the moment while they get that part of the process done to the point where they believe the viewer is ready for the next phase.  

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by LifeGold** [comment]
Question when compiling the client writes the compile without grid support and without a grid is then. How to activate the grid support

**Comment by LifeGold** [comment]
Sorry fix

**Comment by emperorstarfinder** [comment]
Again, please wait until they advise it is safe to build the viewer.  Otherwise you will likely not get the correct configurations.  By building the viewer right now without the instructions which @CaseyraeStarfinder and @BriaKallistaStarfinder will provide you will likely have problems.  

This is why the stable code is not yet in the stable release repository yet.  It is not advisable to be building the viewer until they confirm that it is ready.

Remember patience is a virtue and brings its rewards of success

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by CaseyraeStarfinder** [comment]
Greetings

@LifeGold I happened to notice your repositories for RealLife3D.  You have a repository for a Russian viewer skin.  You do not need a separate skin as the ability to translate into the Russian language is already built into the viewer.  

Whenever we develop code it is easy as a developer to either over think and over develop and forget about what the end user needs or we automatically quickly assume there are things we need that we really do not need at all.  

You also need to be careful not to over modify the viewer code as you will create unintended bugs of your own.  For example you shouldn't over modify code relating to the UI as this will cause bugs in-world for end users including bugs that will affect inventory.

In most cases if you have a feature idea you want in your viewer for your grid it might be better to open a feature request issue here and let our core team implement it in the viewer or determine if its already there in some way.  This way you minimize unintended and accidental bugs.

Best Regards,
Caseyrae Starfinder
Governing Body Vice Chair (Europe)
Core Developer
Viewer Developer Work Group Leader
Viewer Development Work Group
Second Galaxy Development Team
Email: caseyrae@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
Closing as this appears to be resolved

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com
